services:
  db:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: cwsadmin
      POSTGRES_PASSWORD: CarolinaWings1767RB!
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart:
      unless-stopped
  app:
    container_name: spring
    image: openjdk-21:latest
    environment:
      
networks:
  db:
    driver: bridge

volumes:
  db:
