FROM maven:3.9.4-eclipse-temurin-21

WORKDIR /app

COPY .mvn/ .

COPY pom.xml .

COPY mvnw .

RUN chmod +x mvnw

RUN ["mvn", "dependency:go-offline", "-B"]

COPY . .

EXPOSE 8080

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]




