### Get company to get All companies
GET http://localhost:8080/admin/companies

### Get to get a company by ID

GET http://localhost:8080/admin/companies/1

### POST request to create a company
POST http://localhost:8080/admin/companies
Content-Type: application/json

{
  "name": "Carolina Wings - Redbank",
  "address": "Red Bank, SC",
  "logoURL": "https://example.com/logo.png",
  "phoneNumber": "8038080488",
  "industry": "Food Service"
}

### DELETE request to delete a company by id

DELETE localhost:8080/admin/companies/1

### PUT new company property

PUT http://localhost:8080/admin/companies/2
Content-Type: application/json

{
  "name": "Carolina Wings - Ballentine",
  "address": "Ballentine, SC",
  "logoURL": "https://example.com/logo.png",
  "phoneNumber": "123456789",
  "industry": "Food Service"
}
